name: Build
on:
  push: # Run on push
  pull_request: # Run on pull-request
jobs:
  #
  # Windows build
  #
  build-windows:
    runs-on: windows-latest
    steps:
      #
      # Checkout the repository
      #
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      #
      # Configure MSVC
      #
      - name: Configure MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          spectre: true
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true
          version: 6.4.*
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: python -m pip install meson==1.6.0 ninja
      - name: Configure Project
        run: meson setup builddir/
      - name: Build
        run: meson build -C builddir/ -v
      - name: List files
        run: Get-ChildItem -Recurse
